### ISSUE TITLE
ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by JohnChu101** [markolofsen/py_translator#10]
What can I do with this error?

**Comment by markolofsen** [comment]
Try make your text shortener

**Comment by JohnChu101** [comment]
> 
> 
> Try make your text shortener

I can't even translate a word.
I think I made my request too frequently. i made around 100 within one moment and did it several times in a row.
What I want to know is, is it possible for Google to unblock me?
And which one is better? Requesting 10 bulk translation with around 15 lines each, or 2 bulk translation with around 70 lines each?

**Comment by Vide459** [comment]
> Try make your text shortener

Hi can I know the text length limit in the py_translator.

**Comment by sadon** [comment]
Seems like it is a Google ban, the same stuff

**Comment by markolofsen** [comment]
done
