### ISSUE TITLE
Thread error

### ISSUE THREAD

**Issue by HahaLun** [markolofsen/py_translator#11]
I got threading error with below code

code: 
TEXTLIB().translator(is_html=False, text='aplomb', lang_to='zh-TW', proxy=False)

error message:
![image](https://user-images.githubusercontent.com/33598197/50055983-d57a6f00-0190-11e9-89cd-63d80458cdc7.png)

**Comment by markolofsen** [comment]
Try make your text shortener

**Comment by markolofsen** [comment]
Try to use something like this:
```
from py_translator import Translator
s = Translator().translate(text='Hello my friend', dest='es').text
print(s)
```
